version: '3.8'

services:
  db:
    image: postgres:15 # Use the stable version of PostgreSQL
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data # Persistent storage
      - ./docker/pg-init-scripts:/docker-entrypoint-initdb.d # Initialization scripts
    networks:
      - medical-no-show-network

  pgadmin: # Optional GUI for database management
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - medical-no-show-network

networks:
  medical-no-show-network:
    driver: bridge

volumes:
  postgres-data:
