version: '3.8' # Specify Docker Compose version
services:
  db:
    image: postgres:17 # Use the latest stable PostgreSQL version (check compatibility)
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER} # User from environment variable
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # Password from environment variable
      POSTGRES_DB: ${POSTGRES_DB} # Database name from environment variable
    ports:
      - "5432:5432" # Map host port 5432 to container port 5432
    volumes:
      - pgdata:/var/lib/postgresql/data # Persistent storage for PostgreSQL data
    networks:
      - my-proj-network # Custom network for service communication

networks:
  my-proj-network: # Define a custom network for this project
    driver: bridge

volumes:
  pgdata: # Persistent volume for the PostgreSQL database
