version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data # Persistent storage for database data
      - ./pg-init-scripts:/docker-entrypoint-initdb.d # Initialization scripts
    networks:
      - medical-no-show-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - medical-no-show-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin

networks:
  medical-no-show-network:
    driver: bridge

volumes:
  postgres-data:
  pgadmin-data:
