version: '3.8'

services:
  db:
    image: postgres:15 # Use the stable version of PostgreSQL
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER} # Defined in the .env file
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432" # Expose the database on the default port
    volumes:
      - postgres-data:/var/lib/postgresql/data # Persistent storage for database
      - ./docker/pg-init-scripts:/docker-entrypoint-initdb.d # Initialization scripts
    networks:
      - medical-no-show-network

  pgadmin:
    image: dpage/pgadmin4 # Lightweight web-based GUI for managing PostgreSQL
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL} # Admin email from .env
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD} # Admin password from .env
    ports:
      - "8080:80" # Expose pgAdmin on port 8080
    depends_on:
      - db # Ensure PostgreSQL starts first
    networks:
      - medical-no-show-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin # Persistent storage for pgAdmin data

networks:
  medical-no-show-network:
    driver: bridge # Bridge network for service isolation

volumes:
  postgres-data: # Persistent volume for PostgreSQL database data
  pgadmin-data: # Persistent volume for pgAdmin data
